import { giftTierFromStars } from './giftTiers';
import type { GiftEffectDefinition } from './giftEffectCatalogTypes';

/** Builtin showcase catalog — tiers follow coin ranges in giftTiers.ts. */
export const GIFT_EFFECT_CATALOG_BASE: GiftEffectDefinition[] = [
  // Normal · 1–99 · small icon
  { id: 'rose', name: 'Rose', icon: '🌹', stars: 5, tier: giftTierFromStars(5), particleColor: '#fb7185' },
  { id: 'heart', name: 'Heart', icon: '💖', stars: 10, tier: giftTierFromStars(10), particleColor: '#f472b6' },
  {
    id: 'mic',
    name: 'Mic',
    icon: '🎤',
    stars: 25,
    tier: giftTierFromStars(25),
    effectSvgaUrl: '/live-gifts/mic.svga',
    particleColor: '#a78bfa',
  },
  {
    id: 'star',
    name: 'Star',
    icon: '⭐',
    stars: 50,
    tier: giftTierFromStars(50),
    effectSvgaUrl: '/live-gifts/star.svga',
    particleColor: '#fbbf24',
  },
  // Premium · 100–999 · medium SVGA
  {
    id: 'crown',
    name: 'Crown',
    icon: '👑',
    stars: 100,
    tier: giftTierFromStars(100),
    effectSvgaUrl: '/live-gifts/crown.svga',
    particleColor: '#fcd34d',
  },
  {
    id: 'rocket',
    name: 'Rocket',
    icon: '🚀',
    stars: 250,
    tier: giftTierFromStars(250),
    effectSvgaUrl: '/live-gifts/rocket.svga',
    particleColor: '#60a5fa',
  },
  {
    id: 'diamond',
    name: 'Diamond',
    icon: '💎',
    stars: 500,
    tier: giftTierFromStars(500),
    effectSvgaUrl: '/live-gifts/crown.svga',
    particleColor: '#67e8f9',
  },
  {
    id: 'castle',
    name: 'Castle',
    icon: '🏰',
    stars: 999,
    tier: giftTierFromStars(999),
    effectSvgaUrl: '/live-gifts/rocket.svga',
    particleColor: '#c4b5fd',
  },
  // Epic · 1,000–9,999 · full-screen SVGA
  {
    id: 'phoenix',
    name: 'Phoenix',
    icon: '🔥',
    stars: 1_000,
    tier: giftTierFromStars(1_000),
    effectSvgaUrl: '/live-gifts/rocket.svga',
    particleColor: '#fb923c',
  },
  {
    id: 'unicorn',
    name: 'Unicorn',
    icon: '🦄',
    stars: 2_500,
    tier: giftTierFromStars(2_500),
    effectSvgaUrl: '/live-gifts/crown.svga',
    particleColor: '#e879f9',
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    icon: '🌌',
    stars: 5_000,
    tier: giftTierFromStars(5_000),
    effectSvgaUrl: '/live-gifts/star.svga',
    particleColor: '#818cf8',
  },
  // Legendary · 10,000–99,999 · cinematic
  {
    id: 'dragon',
    name: 'Dragon',
    icon: '🐉',
    stars: 10_000,
    tier: giftTierFromStars(10_000),
    effectSvgaUrl: '/live-gifts/rocket.svga',
    particleColor: '#f59e0b',
  },
  {
    id: 'universe',
    name: 'Universe',
    icon: '🪐',
    stars: 50_000,
    tier: giftTierFromStars(50_000),
    effectSvgaUrl: '/live-gifts/crown.svga',
    particleColor: '#38bdf8',
  },
  // Mythic · 100,000+ · multi-stage + global announcement
  {
    id: 'eternity',
    name: 'Eternity',
    icon: '✨',
    stars: 100_000,
    tier: giftTierFromStars(100_000),
    effectSvgaUrl: '/live-gifts/star.svga',
    particleColor: '#f0abfc',
  },
  {
    id: 'divine',
    name: 'Divine',
    icon: '🕊️',
    stars: 250_000,
    tier: giftTierFromStars(250_000),
    effectSvgaUrl: '/live-gifts/crown.svga',
    particleColor: '#fde68a',
  },
];
