import { DeepARInterface } from "./deeparInterface";
import { BeautyAutogenerated } from "./internal/autogenerated/BeautyAutogenerated";
import { PluginRunner } from "./internal/PluginRunner/pluginRunner";
export { version } from "./config";
declare function initializeBeauty(deepaAR: DeepARInterface, rootPath: string): Promise<Beauty>;
declare class Beauty extends BeautyAutogenerated {
    constructor(pluginRunner: PluginRunner);
}
export { initializeBeauty };
