/**
 * ISO 3166-1 alpha-2 countries (English names) for Live discovery filters.
 * Flags are rendered via regional-indicator emoji from the ISO code.
 */
export const WORLD_COUNTRIES: ReadonlyArray<{ name: string; iso: string }> = [
  { name: 'Afghanistan', iso: 'AF' },
  { name: 'Åland Islands', iso: 'AX' },
  { name: 'Albania', iso: 'AL' },
  { name: 'Algeria', iso: 'DZ' },
  { name: 'American Samoa', iso: 'AS' },
  { name: 'Andorra', iso: 'AD' },
  { name: 'Angola', iso: 'AO' },
  { name: 'Anguilla', iso: 'AI' },
  { name: 'Antarctica', iso: 'AQ' },
  { name: 'Antigua and Barbuda', iso: 'AG' },
  { name: 'Argentina', iso: 'AR' },
  { name: 'Armenia', iso: 'AM' },
  { name: 'Aruba', iso: 'AW' },
  { name: 'Australia', iso: 'AU' },
  { name: 'Austria', iso: 'AT' },
  { name: 'Azerbaijan', iso: 'AZ' },
  { name: 'Bahamas', iso: 'BS' },
  { name: 'Bahrain', iso: 'BH' },
  { name: 'Bangladesh', iso: 'BD' },
  { name: 'Barbados', iso: 'BB' },
  { name: 'Belarus', iso: 'BY' },
  { name: 'Belgium', iso: 'BE' },
  { name: 'Belize', iso: 'BZ' },
  { name: 'Benin', iso: 'BJ' },
  { name: 'Bermuda', iso: 'BM' },
  { name: 'Bhutan', iso: 'BT' },
  { name: 'Bolivia', iso: 'BO' },
  { name: 'Bosnia and Herzegovina', iso: 'BA' },
  { name: 'Botswana', iso: 'BW' },
  { name: 'Bouvet Island', iso: 'BV' },
  { name: 'Brazil', iso: 'BR' },
  { name: 'British Indian Ocean Territory', iso: 'IO' },
  { name: 'Brunei', iso: 'BN' },
  { name: 'Bulgaria', iso: 'BG' },
  { name: 'Burkina Faso', iso: 'BF' },
  { name: 'Burundi', iso: 'BI' },
  { name: 'Cabo Verde', iso: 'CV' },
  { name: 'Cambodia', iso: 'KH' },
  { name: 'Cameroon', iso: 'CM' },
  { name: 'Canada', iso: 'CA' },
  { name: 'Cayman Islands', iso: 'KY' },
  { name: 'Central African Republic', iso: 'CF' },
  { name: 'Chad', iso: 'TD' },
  { name: 'Chile', iso: 'CL' },
  { name: 'China', iso: 'CN' },
  { name: 'Christmas Island', iso: 'CX' },
  { name: 'Cocos (Keeling) Islands', iso: 'CC' },
  { name: 'Colombia', iso: 'CO' },
  { name: 'Comoros', iso: 'KM' },
  { name: 'Congo', iso: 'CG' },
  { name: 'Congo (DRC)', iso: 'CD' },
  { name: 'Cook Islands', iso: 'CK' },
  { name: 'Costa Rica', iso: 'CR' },
  { name: "Côte d'Ivoire", iso: 'CI' },
  { name: 'Croatia', iso: 'HR' },
  { name: 'Cuba', iso: 'CU' },
  { name: 'Curaçao', iso: 'CW' },
  { name: 'Cyprus', iso: 'CY' },
  { name: 'Czechia', iso: 'CZ' },
  { name: 'Denmark', iso: 'DK' },
  { name: 'Djibouti', iso: 'DJ' },
  { name: 'Dominica', iso: 'DM' },
  { name: 'Dominican Republic', iso: 'DO' },
  { name: 'Ecuador', iso: 'EC' },
  { name: 'Egypt', iso: 'EG' },
  { name: 'El Salvador', iso: 'SV' },
  { name: 'Equatorial Guinea', iso: 'GQ' },
  { name: 'Eritrea', iso: 'ER' },
  { name: 'Estonia', iso: 'EE' },
  { name: 'Eswatini', iso: 'SZ' },
  { name: 'Ethiopia', iso: 'ET' },
  { name: 'Falkland Islands', iso: 'FK' },
  { name: 'Faroe Islands', iso: 'FO' },
  { name: 'Fiji', iso: 'FJ' },
  { name: 'Finland', iso: 'FI' },
  { name: 'France', iso: 'FR' },
  { name: 'French Guiana', iso: 'GF' },
  { name: 'French Polynesia', iso: 'PF' },
  { name: 'French Southern Territories', iso: 'TF' },
  { name: 'Gabon', iso: 'GA' },
  { name: 'Gambia', iso: 'GM' },
  { name: 'Georgia', iso: 'GE' },
  { name: 'Germany', iso: 'DE' },
  { name: 'Ghana', iso: 'GH' },
  { name: 'Gibraltar', iso: 'GI' },
  { name: 'Greece', iso: 'GR' },
  { name: 'Greenland', iso: 'GL' },
  { name: 'Grenada', iso: 'GD' },
  { name: 'Guadeloupe', iso: 'GP' },
  { name: 'Guam', iso: 'GU' },
  { name: 'Guatemala', iso: 'GT' },
  { name: 'Guernsey', iso: 'GG' },
  { name: 'Guinea', iso: 'GN' },
  { name: 'Guinea-Bissau', iso: 'GW' },
  { name: 'Guyana', iso: 'GY' },
  { name: 'Haiti', iso: 'HT' },
  { name: 'Heard Island and McDonald Islands', iso: 'HM' },
  { name: 'Holy See', iso: 'VA' },
  { name: 'Honduras', iso: 'HN' },
  { name: 'Hong Kong', iso: 'HK' },
  { name: 'Hungary', iso: 'HU' },
  { name: 'Iceland', iso: 'IS' },
  { name: 'India', iso: 'IN' },
  { name: 'Indonesia', iso: 'ID' },
  { name: 'Iran', iso: 'IR' },
  { name: 'Iraq', iso: 'IQ' },
  { name: 'Ireland', iso: 'IE' },
  { name: 'Isle of Man', iso: 'IM' },
  { name: 'Israel', iso: 'IL' },
  { name: 'Italy', iso: 'IT' },
  { name: 'Jamaica', iso: 'JM' },
  { name: 'Japan', iso: 'JP' },
  { name: 'Jersey', iso: 'JE' },
  { name: 'Jordan', iso: 'JO' },
  { name: 'Kazakhstan', iso: 'KZ' },
  { name: 'Kenya', iso: 'KE' },
  { name: 'Kiribati', iso: 'KI' },
  { name: 'Kuwait', iso: 'KW' },
  { name: 'Kyrgyzstan', iso: 'KG' },
  { name: 'Laos', iso: 'LA' },
  { name: 'Latvia', iso: 'LV' },
  { name: 'Lebanon', iso: 'LB' },
  { name: 'Lesotho', iso: 'LS' },
  { name: 'Liberia', iso: 'LR' },
  { name: 'Libya', iso: 'LY' },
  { name: 'Liechtenstein', iso: 'LI' },
  { name: 'Lithuania', iso: 'LT' },
  { name: 'Luxembourg', iso: 'LU' },
  { name: 'Macao', iso: 'MO' },
  { name: 'Madagascar', iso: 'MG' },
  { name: 'Malawi', iso: 'MW' },
  { name: 'Malaysia', iso: 'MY' },
  { name: 'Maldives', iso: 'MV' },
  { name: 'Mali', iso: 'ML' },
  { name: 'Malta', iso: 'MT' },
  { name: 'Marshall Islands', iso: 'MH' },
  { name: 'Martinique', iso: 'MQ' },
  { name: 'Mauritania', iso: 'MR' },
  { name: 'Mauritius', iso: 'MU' },
  { name: 'Mayotte', iso: 'YT' },
  { name: 'Mexico', iso: 'MX' },
  { name: 'Micronesia', iso: 'FM' },
  { name: 'Moldova', iso: 'MD' },
  { name: 'Monaco', iso: 'MC' },
  { name: 'Mongolia', iso: 'MN' },
  { name: 'Montenegro', iso: 'ME' },
  { name: 'Montserrat', iso: 'MS' },
  { name: 'Morocco', iso: 'MA' },
  { name: 'Mozambique', iso: 'MZ' },
  { name: 'Myanmar', iso: 'MM' },
  { name: 'Namibia', iso: 'NA' },
  { name: 'Nauru', iso: 'NR' },
  { name: 'Nepal', iso: 'NP' },
  { name: 'Netherlands', iso: 'NL' },
  { name: 'New Caledonia', iso: 'NC' },
  { name: 'New Zealand', iso: 'NZ' },
  { name: 'Nicaragua', iso: 'NI' },
  { name: 'Niger', iso: 'NE' },
  { name: 'Nigeria', iso: 'NG' },
  { name: 'Niue', iso: 'NU' },
  { name: 'Norfolk Island', iso: 'NF' },
  { name: 'North Korea', iso: 'KP' },
  { name: 'North Macedonia', iso: 'MK' },
  { name: 'Northern Mariana Islands', iso: 'MP' },
  { name: 'Norway', iso: 'NO' },
  { name: 'Oman', iso: 'OM' },
  { name: 'Pakistan', iso: 'PK' },
  { name: 'Palau', iso: 'PW' },
  { name: 'Palestine', iso: 'PS' },
  { name: 'Panama', iso: 'PA' },
  { name: 'Papua New Guinea', iso: 'PG' },
  { name: 'Paraguay', iso: 'PY' },
  { name: 'Peru', iso: 'PE' },
  { name: 'Philippines', iso: 'PH' },
  { name: 'Pitcairn', iso: 'PN' },
  { name: 'Poland', iso: 'PL' },
  { name: 'Portugal', iso: 'PT' },
  { name: 'Puerto Rico', iso: 'PR' },
  { name: 'Qatar', iso: 'QA' },
  { name: 'Réunion', iso: 'RE' },
  { name: 'Romania', iso: 'RO' },
  { name: 'Russia', iso: 'RU' },
  { name: 'Rwanda', iso: 'RW' },
  { name: 'Saint Barthélemy', iso: 'BL' },
  { name: 'Saint Helena', iso: 'SH' },
  { name: 'Saint Kitts and Nevis', iso: 'KN' },
  { name: 'Saint Lucia', iso: 'LC' },
  { name: 'Saint Martin', iso: 'MF' },
  { name: 'Saint Pierre and Miquelon', iso: 'PM' },
  { name: 'Saint Vincent and the Grenadines', iso: 'VC' },
  { name: 'Samoa', iso: 'WS' },
  { name: 'San Marino', iso: 'SM' },
  { name: 'Sao Tome and Principe', iso: 'ST' },
  { name: 'Saudi Arabia', iso: 'SA' },
  { name: 'Senegal', iso: 'SN' },
  { name: 'Serbia', iso: 'RS' },
  { name: 'Seychelles', iso: 'SC' },
  { name: 'Sierra Leone', iso: 'SL' },
  { name: 'Singapore', iso: 'SG' },
  { name: 'Sint Maarten', iso: 'SX' },
  { name: 'Slovakia', iso: 'SK' },
  { name: 'Slovenia', iso: 'SI' },
  { name: 'Solomon Islands', iso: 'SB' },
  { name: 'Somalia', iso: 'SO' },
  { name: 'South Africa', iso: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', iso: 'GS' },
  { name: 'South Korea', iso: 'KR' },
  { name: 'South Sudan', iso: 'SS' },
  { name: 'Spain', iso: 'ES' },
  { name: 'Sri Lanka', iso: 'LK' },
  { name: 'Sudan', iso: 'SD' },
  { name: 'Suriname', iso: 'SR' },
  { name: 'Svalbard and Jan Mayen', iso: 'SJ' },
  { name: 'Sweden', iso: 'SE' },
  { name: 'Switzerland', iso: 'CH' },
  { name: 'Syria', iso: 'SY' },
  { name: 'Taiwan', iso: 'TW' },
  { name: 'Tajikistan', iso: 'TJ' },
  { name: 'Tanzania', iso: 'TZ' },
  { name: 'Thailand', iso: 'TH' },
  { name: 'Timor-Leste', iso: 'TL' },
  { name: 'Togo', iso: 'TG' },
  { name: 'Tokelau', iso: 'TK' },
  { name: 'Tonga', iso: 'TO' },
  { name: 'Trinidad and Tobago', iso: 'TT' },
  { name: 'Tunisia', iso: 'TN' },
  { name: 'Turkey', iso: 'TR' },
  { name: 'Turkmenistan', iso: 'TM' },
  { name: 'Turks and Caicos Islands', iso: 'TC' },
  { name: 'Tuvalu', iso: 'TV' },
  { name: 'Uganda', iso: 'UG' },
  { name: 'Ukraine', iso: 'UA' },
  { name: 'United Arab Emirates', iso: 'AE' },
  { name: 'United Kingdom', iso: 'GB' },
  { name: 'United States', iso: 'US' },
  { name: 'United States Minor Outlying Islands', iso: 'UM' },
  { name: 'Uruguay', iso: 'UY' },
  { name: 'Uzbekistan', iso: 'UZ' },
  { name: 'Vanuatu', iso: 'VU' },
  { name: 'Venezuela', iso: 'VE' },
  { name: 'Vietnam', iso: 'VN' },
  { name: 'Virgin Islands (British)', iso: 'VG' },
  { name: 'Virgin Islands (U.S.)', iso: 'VI' },
  { name: 'Wallis and Futuna', iso: 'WF' },
  { name: 'Western Sahara', iso: 'EH' },
  { name: 'Yemen', iso: 'YE' },
  { name: 'Zambia', iso: 'ZM' },
  { name: 'Zimbabwe', iso: 'ZW' },
];

export const LIVE_COUNTRY_ISO: Record<string, string> = Object.fromEntries(
  WORLD_COUNTRIES.map((c) => [c.name, c.iso]),
);

export const LIVE_COUNTRY_OPTIONS = WORLD_COUNTRIES.map((c) => c.name);

const ISO_BY_LOWER = new Map(
  WORLD_COUNTRIES.flatMap(({ name, iso }) => [
    [name.toLowerCase(), iso],
    [iso.toLowerCase(), iso],
  ]),
);

const NAME_BY_ISO = new Map(WORLD_COUNTRIES.map(({ name, iso }) => [iso, name]));

/** Regional-indicator flag emoji from an ISO country code (e.g. US → 🇺🇸). */
export function countryFlagEmoji(isoOrName?: string | null): string {
  const raw = String(isoOrName || '').trim();
  if (!raw || raw === 'all') return '🌍';
  const iso =
    ISO_BY_LOWER.get(raw.toLowerCase()) ||
    (raw.length === 2 ? raw.toUpperCase() : '');
  if (!/^[A-Z]{2}$/.test(iso)) return '🏳️';
  const points = [...iso].map((ch) => 0x1f1e6 - 65 + ch.charCodeAt(0));
  return String.fromCodePoint(...points);
}

/** "🇺🇸 United States" — flag + name for UI labels. */
export function formatLiveCountryLabel(country?: string | null): string {
  const name = String(country || '').trim();
  if (!name || name === 'all') return `${countryFlagEmoji('all')} All countries`;
  return `${countryFlagEmoji(name)} ${name}`;
}

/** Normalize explicit country / ISO to a canonical display name when known. */
export function normalizeLiveCountryName(explicit?: string | null): string | null {
  const named = String(explicit || '').trim();
  if (!named) return null;
  const iso = ISO_BY_LOWER.get(named.toLowerCase());
  if (iso) return NAME_BY_ISO.get(iso) ?? named;
  return named;
}

/** Stable country label when profile has none (keeps filters useful on demo/local data). */
export function resolveLiveCountry(userId: string, explicit?: string | null): string {
  const known = normalizeLiveCountryName(explicit);
  if (known) return known;
  let hash = 0;
  for (let i = 0; i < userId.length; i += 1) {
    hash = (hash * 31 + userId.charCodeAt(i)) >>> 0;
  }
  return LIVE_COUNTRY_OPTIONS[hash % LIVE_COUNTRY_OPTIONS.length];
}
