import { Router, type IRouter } from "express";
import healthRouter from "./health";
import meRouter from "./me";
import adminRouter from "./admin";
import walletRouter from "./wallet";
import pushRouter from "./push";
import workspaceUnlockRouter from "./workspaceUnlock";
import chatRouter from "./chat";
import streamRouter from "./stream";
import liveSeatsRouter from "./liveSeats";
import liveLifecycleRouter from "./liveLifecycle";
import livePkChallengeRouter from "./livePkChallenge";
import presenceRouter from "./presence";
import livekitRouter from "./livekit";
import tencentRtcRouter from "./tencentRtc";
import uxRouter from "./ux";
import handoffRouter from "./handoff";
import feedRouter from "./feed";
import upstashRouter from "./upstash";
import qstashRouter from "./qstash";
import linearRouter from "./linear";
import youtubeRouter from "./youtube";
import automationRouter from "./automation";
import paymentsRouter from "./payments";
import giftsRouter from "./gifts";
import entitlementsRouter from "./entitlements";
import i18nRouter from "./i18n";
import uiConfigRouter from "./uiConfig";
import adminUiConfigRouter from "./adminUiConfig";
import adminRuntimeConfigRouter from "./adminRuntimeConfig";
import adminControlPlaneRouter from "./admin/index";
import appConfigRouter from "./appConfig";
import uiSessionsRouter from "./uiSessions";
import platformBrandRouter from "./platformBrand";
import aiRouter from "./ai";
import mediaRouter from "./media";
import mongoRouter from "./mongo";
import auroraRouter from "./aurora";
import discordRouter from "./discord";
import { upstashRateLimit } from "../lib/ratelimit";

const router: IRouter = Router();

// Discord must verify Ed25519 + respond within 3s — keep ahead of rate limiting.
router.use(discordRouter);
router.use(upstashRateLimit);
router.use(healthRouter);
router.use(upstashRouter);
router.use(qstashRouter);
router.use(linearRouter);
router.use(livekitRouter);
router.use(tencentRtcRouter);
router.use(youtubeRouter);
router.use(feedRouter);
router.use(mediaRouter);
router.use(mongoRouter);
router.use(auroraRouter);
router.use("/me", meRouter);
router.use("/ui-config", uiConfigRouter);
router.use("/ui-sessions", uiSessionsRouter);
router.use("/app-config", appConfigRouter);
router.use("/admin/ui-config", adminUiConfigRouter);
router.use("/admin/runtime-config", adminRuntimeConfigRouter);
router.use("/admin", adminControlPlaneRouter);
router.use("/admin", adminRouter);
router.use("/wallet", walletRouter);
router.use("/push", pushRouter);
router.use("/workspace", workspaceUnlockRouter);
router.use("/gifts", giftsRouter);
router.use("/entitlements", entitlementsRouter);
router.use("/i18n", i18nRouter);
router.use("/payments", paymentsRouter);
router.use("/chat", chatRouter);
router.use("/stream", streamRouter);
router.use("/live/rooms", liveLifecycleRouter);
router.use("/live/pk/challenges", livePkChallengeRouter);
router.use("/live", liveSeatsRouter);
router.use(presenceRouter);
router.use(uxRouter);
router.use(handoffRouter);
router.use(automationRouter);
router.use(platformBrandRouter);
router.use(aiRouter);

export default router;
