import { Router, type IRouter } from "express";
import healthRouter from "./health";
import meRouter from "./me";
import adminRouter from "./admin";
import walletRouter from "./wallet";
import chatRouter from "./chat";
import streamRouter from "./stream";
import presenceRouter from "./presence";
import livekitRouter from "./livekit";
import uxRouter from "./ux";
import handoffRouter from "./handoff";
import feedRouter from "./feed";
import upstashRouter from "./upstash";
import qstashRouter from "./qstash";
import linearRouter from "./linear";
import youtubeRouter from "./youtube";
import automationRouter from "./automation";
import paymentsRouter from "./payments";
import giftsRouter from "./gifts";
import platformBrandRouter from "./platformBrand";
import aiRouter from "./ai";
import mediaRouter from "./media";
import mongoRouter from "./mongo";
import auroraRouter from "./aurora";
import discordRouter from "./discord";
import { upstashRateLimit } from "../lib/ratelimit";

const router: IRouter = Router();

// Discord must verify Ed25519 + respond within 3s — keep ahead of rate limiting.
router.use(discordRouter);
router.use(upstashRateLimit);
router.use(healthRouter);
router.use(upstashRouter);
router.use(qstashRouter);
router.use(linearRouter);
router.use(livekitRouter);
router.use(youtubeRouter);
router.use(feedRouter);
router.use(mediaRouter);
router.use(mongoRouter);
router.use(auroraRouter);
router.use("/me", meRouter);
router.use("/admin", adminRouter);
router.use("/wallet", walletRouter);
router.use("/gifts", giftsRouter);
router.use("/payments", paymentsRouter);
router.use("/chat", chatRouter);
router.use("/stream", streamRouter);
router.use(presenceRouter);
router.use(uxRouter);
router.use(handoffRouter);
router.use(automationRouter);
router.use(platformBrandRouter);
router.use(aiRouter);

export default router;
