import type { AdminPermission, AdminRole } from "@workspace/api-zod";

export const ADMIN_ROLES: AdminRole[] = [
  "admin_viewer",
  "ui_editor",
  "asset_editor",
  "translation_editor",
  "config_editor",
  "reviewer",
  "publisher",
  "session_manager",
  "secret_operator",
  "security_admin",
  "super_admin",
];

export const ADMIN_PERMISSIONS: AdminPermission[] = [
  "admin.dashboard.read",
  "change_set.read",
  "change_set.create",
  "change_set.edit_own",
  "change_set.submit",
  "change_set.cancel",
  "ui.experience.read",
  "ui.experience.edit",
  "ui.node.edit",
  "ui.component.select",
  "ui.element.edit",
  "ui.layout.edit",
  "ui.theme.edit",
  "ui.token.edit",
  "ui.motion.edit",
  "asset.read",
  "asset.upload",
  "asset.approve",
  "asset.publish",
  "translation.read",
  "translation.edit",
  "translation.review",
  "translation.publish",
  "config.read",
  "config.edit_public",
  "config.edit_private_reference",
  "config.validate",
  "config.activate",
  "session.preview",
  "session.assign",
  "session.end",
  "review.read",
  "review.approve",
  "review.reject",
  "publish.preview",
  "publish.staging",
  "publish.production",
  "publish.rollback",
  "audit.read",
  "access.role.read",
  "access.role.grant",
  "access.role.revoke",
  "secret.metadata.read",
  "secret.reference.edit",
  "secret.write_once",
  "gift.catalog.read",
  "gift.catalog.edit",
  "gift.pricing.edit",
  "gift.pricing.approve",
  "gift.publish",
  "face_effect.read",
  "face_effect.edit",
  "face_effect.approve",
  "face_effect.publish",
  "animation.read",
  "animation.edit",
  "animation.approve",
  "animation.publish",
  "media.upload",
  "media.validate",
  "media.approve",
  "media.publish",
  "performance.read",
  "performance.benchmark",
  "performance.override",
  "rollout.create",
  "rollout.pause",
  "rollout.resume",
  "rollout.rollback",
];

const VIEW: AdminPermission[] = [
  "admin.dashboard.read",
  "change_set.read",
  "ui.experience.read",
  "asset.read",
  "translation.read",
  "config.read",
  "review.read",
  "audit.read",
  "secret.metadata.read",
  "gift.catalog.read",
  "face_effect.read",
  "animation.read",
  "performance.read",
];

export const ROLE_PERMISSIONS: Record<AdminRole, readonly AdminPermission[]> = {
  admin_viewer: VIEW,
  ui_editor: [
    ...VIEW,
    "change_set.create",
    "change_set.edit_own",
    "change_set.submit",
    "change_set.cancel",
    "ui.experience.edit",
    "ui.node.edit",
    "ui.component.select",
    "ui.element.edit",
    "ui.layout.edit",
    "ui.theme.edit",
    "ui.token.edit",
    "ui.motion.edit",
    "session.preview",
  ],
  asset_editor: [
    ...VIEW,
    "change_set.create",
    "change_set.edit_own",
    "change_set.submit",
    "asset.upload",
    "asset.approve",
    "gift.catalog.edit",
    "face_effect.edit",
    "animation.edit",
    "media.upload",
    "media.validate",
    "performance.benchmark",
  ],
  translation_editor: [
    ...VIEW,
    "change_set.create",
    "change_set.edit_own",
    "change_set.submit",
    "translation.edit",
    "translation.review",
  ],
  config_editor: [
    ...VIEW,
    "change_set.create",
    "change_set.edit_own",
    "change_set.submit",
    "config.edit_public",
    "config.edit_private_reference",
    "config.validate",
    "secret.reference.edit",
  ],
  reviewer: [
    ...VIEW,
    "review.approve",
    "review.reject",
    "gift.pricing.approve",
    "face_effect.approve",
    "animation.approve",
    "media.approve",
  ],
  publisher: [
    ...VIEW,
    "publish.preview",
    "publish.staging",
    "publish.production",
    "publish.rollback",
    "config.activate",
    "asset.publish",
    "translation.publish",
    "session.assign",
    "session.end",
    "gift.publish",
    "gift.pricing.edit",
    "face_effect.publish",
    "animation.publish",
    "media.publish",
    "rollout.create",
    "rollout.pause",
    "rollout.resume",
    "rollout.rollback",
    "performance.override",
  ],
  session_manager: [...VIEW, "session.preview", "session.assign", "session.end"],
  secret_operator: [
    ...VIEW,
    "secret.reference.edit",
    "secret.write_once",
    "config.edit_private_reference",
    "config.validate",
  ],
  security_admin: [...VIEW, "access.role.read", "access.role.grant", "access.role.revoke"],
  super_admin: ADMIN_PERMISSIONS,
};

export const STEP_UP_PERMISSIONS = new Set<AdminPermission>([
  "publish.production",
  "publish.rollback",
  "access.role.grant",
  "access.role.revoke",
  "config.activate",
  "secret.write_once",
  "secret.reference.edit",
  "gift.pricing.edit",
  "performance.override",
  "rollout.rollback",
]);

export function permissionsForRoles(roles: AdminRole[]): Set<AdminPermission> {
  const out = new Set<AdminPermission>();
  for (const role of roles) {
    for (const p of ROLE_PERMISSIONS[role]) out.add(p);
  }
  return out;
}

export function publishPermissionForEnvironment(env: string): AdminPermission {
  if (env === "production") return "publish.production";
  if (env === "staging") return "publish.staging";
  return "publish.preview";
}
