import type { AppTemplateSpec, ScaffoldFileDef } from "./appScaffoldTemplates";
import type { AppStackSpec } from "./appStackInference";
import { listAppStacks } from "./appStackInference";

export type StackBuildContext = {
  appId: string;
  appName: string;
  devPort: number;
  message: string;
  envExample: string;
  pipelineManifest: object;
  accessManifest: object;
  structureMap: object;
  template: AppTemplateSpec;
  stack: AppStackSpec;
};

function dartFileName(screenFile: string): string {
  return screenFile.replace(/([a-z])([A-Z])/g, "$1_$2").toLowerCase();
}

function kotlinClassName(screenFile: string): string {
  return screenFile;
}

function swiftFileName(screenFile: string): string {
  return screenFile;
}

function sharedManifestFiles(ctx: StackBuildContext, readme: string, extraConfig: Record<string, unknown> = {}): ScaffoldFileDef[] {
  const { appId, appName, template, stack, devPort } = ctx;
  return [
    {
      path: "README.md",
      role: "doc",
      description: "Run instructions",
      content: readme,
    },
    {
      path: "structure.map.json",
      role: "config",
      description: "Machine-readable folder map",
      content: `${JSON.stringify({ ...ctx.structureMap, stack: stack.stack, template: template.kind, features: template.features, devPort }, null, 2)}\n`,
    },
    { path: ".env.example", role: "env", description: "Environment template", content: ctx.envExample },
    {
      path: ".gitignore",
      role: "config",
      description: "Git ignore rules",
      content: "node_modules\ndist\nbuild\n.env.local\n.DS_Store\n.dart_tool\n.idea\n*.iml\n",
    },
    {
      path: "config/stack.manifest.json",
      role: "config",
      description: "Selected stack + available stacks",
      content: `${JSON.stringify({ selected: stack, available: listAppStacks(), targets: stack.targets }, null, 2)}\n`,
    },
    {
      path: "config/app.manifest.json",
      role: "config",
      description: "App metadata",
      content: `${JSON.stringify({ id: appId, name: appName, stack: stack.stack, template: template.kind, devPort, routes: template.routes, ...extraConfig }, null, 2)}\n`,
    },
    {
      path: "pipeline/manifest.json",
      role: "pipeline",
      description: "CI/CD pipeline stages",
      content: `${JSON.stringify(ctx.pipelineManifest, null, 2)}\n`,
    },
    {
      path: "access/manifest.json",
      role: "access",
      description: "Roles and permissions",
      content: `${JSON.stringify(ctx.accessManifest, null, 2)}\n`,
    },
  ];
}

function rnScreen(screenFile: string, label: string, appName: string, appId: string): string {
  if (screenFile === "HomeScreen") {
    return `import { StyleSheet, Text, View } from "react-native";

export function HomeScreen() {
  return (
    <View style={styles.screen}>
      <Text style={styles.title}>${appName}</Text>
      <Text style={styles.sub}>${label} — React Native (Expo)</Text>
      <View style={styles.card}><Text style={styles.cardText}>App id: ${appId}</Text></View>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, padding: 20, gap: 12, backgroundColor: "#070b14" },
  title: { fontSize: 28, fontWeight: "700", color: "#e8eeff" },
  sub: { fontSize: 14, color: "#8b9bc0" },
  card: { backgroundColor: "#10182a", borderRadius: 12, padding: 16, borderWidth: 1, borderColor: "#1e2a44" },
  cardText: { color: "#c8d4ff", fontSize: 13 },
});
`;
  }
  return `import { StyleSheet, Text, View } from "react-native";

export function ${screenFile}() {
  return (
    <View style={styles.screen}>
      <Text style={styles.title}>${label}</Text>
      <Text style={styles.sub}>Working ${screenFile} screen</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, padding: 20, backgroundColor: "#070b14" },
  title: { fontSize: 24, fontWeight: "700", color: "#e8eeff", marginBottom: 8 },
  sub: { fontSize: 14, color: "#8b9bc0" },
});
`;
}

export function buildReactNativeAppFiles(ctx: StackBuildContext): ScaffoldFileDef[] {
  const { appId, appName, template, stack } = ctx;
  const pkgName = `@workspace/${appId}`;
  const tabScreens = template.routes
    .map((r) => {
      const comp = r.file;
      return `      <Tab.Screen name="${r.label}" component={${comp}} options={{ title: "${r.label}" }} />`;
    })
    .join("\n");
  const imports = template.routes.map((r) => `import { ${r.file} } from "./src/screens/${r.file}";`).join("\n");

  const files: ScaffoldFileDef[] = [
    ...sharedManifestFiles(
      ctx,
      `# ${appName}

**${stack.label}** — generated by the dev workspace agent.

## Run

\`\`\`bash
pnpm install
pnpm --filter ${pkgName} start
\`\`\`

Then press \`i\` for iOS simulator or \`a\` for Android emulator (requires Expo Go or dev client).

## Features

${template.features.map((f) => `- ${f}`).join("\n")}
`,
      { expo: true },
    ),
    {
      path: "package.json",
      role: "config",
      description: "Expo + React Native manifest",
      content: `${JSON.stringify(
        {
          name: pkgName,
          version: "0.0.0",
          private: true,
          main: "index.js",
          scripts: {
            start: "expo start",
            android: "expo start --android",
            ios: "expo start --ios",
            typecheck: "tsc --noEmit",
          },
          dependencies: {
            "@react-navigation/bottom-tabs": "^7.2.0",
            "@react-navigation/native": "^7.0.14",
            expo: "~52.0.0",
            "expo-status-bar": "~2.0.0",
            react: "19.1.0",
            "react-native": "0.76.3",
            "react-native-safe-area-context": "4.12.0",
            "react-native-screens": "~4.4.0",
          },
          devDependencies: {
            "@types/react": "~19.0.0",
            typescript: "~5.9.3",
          },
        },
        null,
        2,
      )}\n`,
    },
    {
      path: "app.json",
      role: "config",
      description: "Expo app config",
      content: `${JSON.stringify(
        {
          expo: {
            name: appName,
            slug: appId,
            version: "1.0.0",
            orientation: "portrait",
            userInterfaceStyle: "dark",
            splash: { backgroundColor: "#070b14" },
            ios: { supportsTablet: true, bundleIdentifier: `com.workspace.${appId.replace(/-/g, "")}` },
            android: { adaptiveIcon: { backgroundColor: "#070b14" }, package: `com.workspace.${appId.replace(/-/g, "")}` },
          },
        },
        null,
        2,
      )}\n`,
    },
    {
      path: "tsconfig.json",
      role: "config",
      description: "TypeScript config",
      content: `${JSON.stringify({ extends: "expo/tsconfig.base", include: ["**/*.ts", "**/*.tsx"], compilerOptions: { strict: true } }, null, 2)}\n`,
    },
    {
      path: "index.js",
      role: "code",
      description: "Expo entry",
      content: `import { registerRootComponent } from "expo";
import App from "./App";

registerRootComponent(App);
`,
    },
    {
      path: "App.tsx",
      role: "code",
      description: "Root navigation — bottom tabs",
      content: `import { NavigationContainer, DarkTheme } from "@react-navigation/native";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { StatusBar } from "expo-status-bar";
import { SafeAreaProvider } from "react-native-safe-area-context";
${imports}

const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <SafeAreaProvider>
      <NavigationContainer theme={DarkTheme}>
        <StatusBar style="light" />
        <Tab.Navigator screenOptions={{ headerStyle: { backgroundColor: "#0b1020" }, tabBarStyle: { backgroundColor: "#0b1020", borderTopColor: "#1e2a44" } }}>
${tabScreens}
        </Tab.Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
  );
}
`,
    },
    {
      path: "src/lib/api.ts",
      role: "code",
      description: "API client",
      content: `const API_URL = process.env.EXPO_PUBLIC_API_URL || "http://127.0.0.1:5001";

export async function checkApiHealth(): Promise<boolean> {
  try {
    const res = await fetch(\`\${API_URL}/api/health\`);
    return res.ok;
  } catch {
    return false;
  }
}
`,
    },
  ];

  for (const route of template.routes) {
    files.push({
      path: `src/screens/${route.file}.tsx`,
      role: "code",
      description: `${route.label} screen`,
      content: `${rnScreen(route.file, route.label, appName, appId)}\n`,
    });
  }

  return files;
}

function flutterScreen(screenFile: string, label: string, appName: string, appId: string): string {
  const className = screenFile;
  if (screenFile === "HomeScreen") {
    return `import 'package:flutter/material.dart';

class ${className} extends StatelessWidget {
  const ${className}({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('${appName}', style: Theme.of(context).textTheme.headlineMedium),
              const SizedBox(height: 8),
              Text('${label} — Flutter', style: TextStyle(color: Colors.grey.shade400)),
              const SizedBox(height: 16),
              Card(
                color: const Color(0xFF10182A),
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Text('App id: ${appId}', style: const TextStyle(color: Color(0xFFC8D4FF))),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
`;
  }
  return `import 'package:flutter/material.dart';

class ${className} extends StatelessWidget {
  const ${className}({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('${label}', style: Theme.of(context).textTheme.headlineSmall),
              const SizedBox(height: 8),
              Text('Working ${className}', style: TextStyle(color: Colors.grey.shade400)),
            ],
          ),
        ),
      ),
    );
  }
}
`;
}

export function buildFlutterAppFiles(ctx: StackBuildContext): ScaffoldFileDef[] {
  const { appId, appName, template, stack } = ctx;
  const pkgId = appId.replace(/-/g, "_");
  const navItems = template.routes
    .map((r) => `    _NavItem(icon: Icons.circle, label: '${r.label}', builder: () => const ${r.file}()),`)
    .join("\n");

  const files: ScaffoldFileDef[] = [
    ...sharedManifestFiles(
      ctx,
      `# ${appName}

**${stack.label}** — generated by the dev workspace agent.

## Run

\`\`\`bash
cd artifacts/${appId}
flutter pub get
flutter run
\`\`\`

If platform folders are missing: \`flutter create . --project-name ${pkgId}\`

## Features

${template.features.map((f) => `- ${f}`).join("\n")}
`,
      { flutter: true },
    ),
    {
      path: "pubspec.yaml",
      role: "config",
      description: "Flutter package manifest",
      content: `name: ${pkgId}
description: ${appName}
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
`,
    },
    {
      path: "analysis_options.yaml",
      role: "config",
      description: "Dart analyzer rules",
      content: `include: package:flutter_lints/flutter.yaml
`,
    },
    {
      path: "lib/main.dart",
      role: "code",
      description: "Flutter entry",
      content: `import 'package:flutter/material.dart';
import 'app.dart';

void main() {
  runApp(const ${toPascal(appName)}App());
}
`,
    },
    {
      path: "lib/app.dart",
      role: "code",
      description: "Material app + bottom navigation",
      content: `import 'package:flutter/material.dart';
${template.routes.map((r) => `import 'screens/${dartFileName(r.file)}.dart';`).join("\n")}

class ${toPascal(appName)}App extends StatelessWidget {
  const ${toPascal(appName)}App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${appName}',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.dark,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF6EA8FF), brightness: Brightness.dark),
        useMaterial3: true,
      ),
      home: const _RootShell(),
    );
  }
}

class _RootShell extends StatefulWidget {
  const _RootShell();

  @override
  State<_RootShell> createState() => _RootShellState();
}

class _RootShellState extends State<_RootShell> {
  int _index = 0;
  late final List<_NavItem> _items = [
${navItems}
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _items[_index].builder(),
      bottomNavigationBar: NavigationBar(
        selectedIndex: _index,
        onDestinationSelected: (i) => setState(() => _index = i),
        destinations: _items.map((e) => NavigationDestination(icon: e.icon, label: e.label)).toList(),
      ),
    );
  }
}

class _NavItem {
  const _NavItem({required this.icon, required this.label, required this.builder});
  final IconData icon;
  final String label;
  final Widget Function() builder;
}
`,
    },
    {
      path: "lib/services/api.dart",
      role: "code",
      description: "API health check",
      content: `import 'package:http/http.dart' as http;

const apiBase = String.fromEnvironment('API_URL', defaultValue: 'http://127.0.0.1:5001');

Future<bool> checkApiHealth() async {
  try {
    final res = await http.get(Uri.parse('\$apiBase/api/health'));
    return res.statusCode == 200;
  } catch (_) {
    return false;
  }
}
`,
    },
  ];

  for (const route of template.routes) {
    files.push({
      path: `lib/screens/${dartFileName(route.file)}.dart`,
      role: "code",
      description: `${route.label} screen`,
      content: flutterScreen(route.file, route.label, appName, appId),
    });
  }

  return files;
}

function toPascal(name: string): string {
  return name.replace(/(^|[^a-zA-Z0-9]+)([a-zA-Z0-9])/g, (_, __, c) => c.toUpperCase()).replace(/[^a-zA-Z0-9]/g, "") || "App";
}

export function buildAndroidNativeAppFiles(ctx: StackBuildContext): ScaffoldFileDef[] {
  const { appId, appName, template, stack } = ctx;
  const pkg = appId.replace(/-/g, "");
  const pkgPath = `com/workspace/${pkg}`.replace(/\//g, ".");
  const pkgDir = `com/workspace/${pkg}`;

  const screenFiles: ScaffoldFileDef[] = template.routes.map((route) => ({
    path: `app/src/main/java/${pkgDir}/ui/screens/${kotlinClassName(route.file)}.kt`,
    role: "code" as const,
    description: `${route.label} Compose screen`,
    content: `package ${pkgPath}.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

@Composable
fun ${kotlinClassName(route.file)}() {
  Column(Modifier.fillMaxSize().padding(20.dp)) {
    Text("${route.label}", style = MaterialTheme.typography.headlineSmall)
    Spacer(Modifier.height(8.dp))
    Text("Working ${kotlinClassName(route.file)} screen", color = MaterialTheme.colorScheme.onSurfaceVariant)
  }
}
`,
  }));

  const destinations = template.routes
    .map((r, i) => `        NavigationBarItem(selected = selected == ${i}, onClick = { selected = ${i} }, icon = { Text("${r.label.charAt(0)}") }, label = { Text("${r.label}") })`)
    .join(",\n");

  const whenScreens = template.routes
    .map((r, i) => `        ${i} -> ${kotlinClassName(r.file)}()`)
    .join("\n");

  const files: ScaffoldFileDef[] = [
    ...sharedManifestFiles(
      ctx,
      `# ${appName}

**${stack.label}** — generated by the dev workspace agent.

## Run

\`\`\`bash
cd artifacts/${appId}
./gradlew :app:installDebug
\`\`\`

Requires Android Studio / SDK. Open folder in Android Studio to run on emulator or device.

## Features

${template.features.map((f) => `- ${f}`).join("\n")}
`,
      { android: true, package: pkgPath },
    ),
    {
      path: "settings.gradle.kts",
      role: "config",
      description: "Gradle settings",
      content: `rootProject.name = "${appName.replace(/"/g, "")}"
include(":app")
`,
    },
    {
      path: "build.gradle.kts",
      role: "config",
      description: "Root Gradle build",
      content: `plugins {
  id("com.android.application") version "8.7.2" apply false
  id("org.jetbrains.kotlin.android") version "2.0.21" apply false
}
`,
    },
    {
      path: "gradle.properties",
      role: "config",
      description: "Gradle properties",
      content: `org.gradle.jvmargs=-Xmx2048m
android.useAndroidX=true
kotlin.code.style=official
`,
    },
    {
      path: "app/build.gradle.kts",
      role: "config",
      description: "App module Gradle",
      content: `plugins {
  id("com.android.application")
  id("org.jetbrains.kotlin.android")
}

android {
  namespace = "${pkgPath}"
  compileSdk = 35
  defaultConfig {
    applicationId = "${pkgPath}"
    minSdk = 26
    targetSdk = 35
    versionCode = 1
    versionName = "1.0"
  }
  buildFeatures { compose = true }
  compileOptions { sourceCompatibility = JavaVersion.VERSION_17; targetCompatibility = JavaVersion.VERSION_17 }
  kotlinOptions { jvmTarget = "17" }
  composeOptions { kotlinCompilerExtensionVersion = "1.5.15" }
}

dependencies {
  implementation(platform("androidx.compose:compose-bom:2024.10.01"))
  implementation("androidx.activity:activity-compose:1.9.3")
  implementation("androidx.compose.material3:material3")
  implementation("androidx.compose.ui:ui")
  implementation("androidx.compose.ui:ui-tooling-preview")
  debugImplementation("androidx.compose.ui:ui-tooling")
}
`,
    },
    {
      path: "app/src/main/AndroidManifest.xml",
      role: "config",
      description: "Android manifest",
      content: `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <application android:label="${appName}" android:theme="@android:style/Theme.Material.NoActionBar">
    <activity android:name=".MainActivity" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
  </application>
</manifest>
`,
    },
    {
      path: `app/src/main/java/${pkgDir}/MainActivity.kt`,
      role: "code",
      description: "Main activity — Compose navigation",
      content: `package ${pkgPath}

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import ${pkgPath}.ui.screens.*
import ${pkgPath}.ui.theme.AppTheme

class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContent {
      AppTheme {
        var selected by remember { mutableIntStateOf(0) }
        Scaffold(
          bottomBar = {
            NavigationBar {
${destinations}
            }
          }
        ) { padding ->
          Box(Modifier.padding(padding)) {
            when (selected) {
${whenScreens}
            }
          }
        }
      }
    }
  }
}
`,
    },
    {
      path: `app/src/main/java/${pkgDir}/ui/theme/Theme.kt`,
      role: "code",
      description: "Material 3 dark theme",
      content: `package ${pkgPath}.ui.theme

import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

private val DarkColors = darkColorScheme(primary = Color(0xFF6EA8FF), background = Color(0xFF070B14))

@Composable
fun AppTheme(content: @Composable () -> Unit) {
  MaterialTheme(colorScheme = DarkColors, content = content)
}
`,
    },
    ...screenFiles,
  ];

  return files;
}

export function buildIosNativeAppFiles(ctx: StackBuildContext): ScaffoldFileDef[] {
  const { appId, appName, template, stack } = ctx;
  const product = toPascal(appName);
  const bundleId = `com.workspace.${appId.replace(/-/g, "")}`;

  const tabViews = template.routes
    .map((r) => `            ${r.file}().tabItem { Label("${r.label}", systemImage: "circle") }`)
    .join("\n");

  const screenFiles: ScaffoldFileDef[] = template.routes.map((route) => ({
    path: `ios/App/Screens/${swiftFileName(route.file)}.swift`,
    role: "code" as const,
    description: `${route.label} SwiftUI screen`,
    content: `import SwiftUI

struct ${route.file}: View {
  var body: some View {
    NavigationStack {
      VStack(alignment: .leading, spacing: 12) {
        Text("${route.label}").font(.largeTitle.bold())
        Text("Working ${route.file} — SwiftUI").foregroundStyle(.secondary)
      }
      .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
      .padding(20)
      .background(Color(red: 0.03, green: 0.04, blue: 0.08))
    }
  }
}
`,
  }));

  const files: ScaffoldFileDef[] = [
    ...sharedManifestFiles(
      ctx,
      `# ${appName}

**${stack.label}** — generated by the dev workspace agent.

## Run

1. Install [XcodeGen](https://github.com/yonaskolb/XcodeGen): \`brew install xcodegen\`
2. \`cd artifacts/${appId}/ios && xcodegen generate\`
3. Open \`${product}.xcodeproj\` in Xcode and Run (⌘R)

Or create a new iOS App in Xcode and copy \`ios/App/\` sources.

## Features

${template.features.map((f) => `- ${f}`).join("\n")}
`,
      { ios: true, bundleId },
    ),
    {
      path: "ios/project.yml",
      role: "config",
      description: "XcodeGen project spec",
      content: `name: ${product}
options:
  bundleIdPrefix: com.workspace
targets:
  ${product}:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [App]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ${bundleId}
      SWIFT_VERSION: "5.9"
`,
    },
    {
      path: "ios/App/App.swift",
      role: "code",
      description: "SwiftUI app entry",
      content: `import SwiftUI

@main
struct ${product}App: App {
  var body: some Scene {
    WindowGroup {
      ContentView()
    }
  }
}
`,
    },
    {
      path: "ios/App/ContentView.swift",
      role: "code",
      description: "Tab navigation shell",
      content: `import SwiftUI

struct ContentView: View {
  var body: some View {
    TabView {
${tabViews}
    }
    .preferredColorScheme(.dark)
  }
}
`,
    },
    ...screenFiles,
  ];

  return files;
}

export function buildCapacitorAppFiles(ctx: StackBuildContext, webFiles: ScaffoldFileDef[]): ScaffoldFileDef[] {
  const { appId, appName, stack } = ctx;
  const pkgName = `@workspace/${appId}`;
  const extra: ScaffoldFileDef[] = [
    {
      path: "capacitor.config.ts",
      role: "config",
      description: "Capacitor native shell config",
      content: `import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "com.workspace.${appId.replace(/-/g, "")}",
  appName: "${appName}",
  webDir: "dist",
  server: { androidScheme: "https" },
};

export default config;
`,
    },
    {
      path: "config/stack.manifest.json",
      role: "config",
      description: "Capacitor hybrid stack",
      content: `${JSON.stringify({ selected: stack, available: listAppStacks(), targets: stack.targets, wraps: "react-web" }, null, 2)}\n`,
    },
  ];

  const patched = webFiles.map((f) => {
    if (f.path !== "package.json") return f;
    const pkg = JSON.parse(f.content) as Record<string, unknown>;
    const scripts = (pkg.scripts as Record<string, string>) || {};
    scripts["cap:sync"] = "pnpm build && npx cap sync";
    scripts["cap:ios"] = "npx cap open ios";
    scripts["cap:android"] = "npx cap open android";
    const deps = (pkg.dependencies as Record<string, string>) || {};
    deps["@capacitor/core"] = "^6.2.0";
    deps["@capacitor/cli"] = "^6.2.0";
    const devDeps = (pkg.devDependencies as Record<string, string>) || {};
    devDeps["@capacitor/android"] = "^6.2.0";
    devDeps["@capacitor/ios"] = "^6.2.0";
    return { ...f, content: `${JSON.stringify({ ...pkg, scripts, dependencies: deps, devDependencies: devDeps }, null, 2)}\n` };
  });

  const readmeIdx = patched.findIndex((f) => f.path === "README.md");
  if (readmeIdx >= 0) {
    patched[readmeIdx] = {
      ...patched[readmeIdx],
      content: `# ${appName}

**${stack.label}** — React web app + Capacitor iOS/Android shells.

## Run web

\`\`\`bash
pnpm install
pnpm --filter ${pkgName} dev
\`\`\`

## Native shells

\`\`\`bash
pnpm --filter ${pkgName} cap:sync
pnpm --filter ${pkgName} cap:ios    # or cap:android
\`\`\`
`,
    };
  }

  return [...patched.filter((f) => f.path !== "config/stack.manifest.json"), ...extra];
}
