import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { generateText } from "ai";
import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { createChangeSet } from "./changeSetService";
import { addOrUpdateItem } from "./changeItemService";
import { uploadLocalAsset } from "./mediaApprovalService";
import { isDevWorkspaceEnabled } from "./workspaceConfigService";
import { workspacePersistDir } from "./workspaceRuntimeService";

const AGENT_DIR = workspacePersistDir("design-agent");

export type DesignAgentJob = {
  id: string;
  status: "queued" | "running" | "ready" | "failed";
  screenName: string;
  fileName: string;
  mimeType: string;
  designAssetId: string;
  designPreviewUrl: string;
  targetResourceId?: string | null;
  spec?: Record<string, unknown>;
  componentCode?: string;
  previewHtml?: string;
  catalogResourceId?: string | null;
  fidelityNotes?: string;
  changeSetId?: string | null;
  error?: string | null;
  createdAt: string;
  updatedAt: string;
};

function agentEnabled(): boolean {
  return isDevWorkspaceEnabled();
}

function geminiModel() {
  const apiKey = String(process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY || "").trim();
  if (!apiKey) return null;
  const google = createGoogleGenerativeAI({ apiKey });
  return google("gemini-2.5-flash");
}

function jobPath(id: string): string {
  return path.join(AGENT_DIR, `${id}.json`);
}

function writeJob(job: DesignAgentJob): void {
  mkdirSync(AGENT_DIR, { recursive: true });
  writeFileSync(jobPath(job.id), JSON.stringify(job, null, 2));
}

export function readDesignAgentJob(id: string): DesignAgentJob | null {
  if (!agentEnabled()) return null;
  const file = jobPath(id);
  if (!existsSync(file)) return null;
  try {
    return JSON.parse(readFileSync(file, "utf8")) as DesignAgentJob;
  } catch {
    return null;
  }
}

function slugName(name: string): string {
  return name.replace(/\.[^.]+$/, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "screen";
}

function extractJson(text: string): Record<string, unknown> | null {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const raw = (fenced?.[1] || text).trim();
  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    const start = raw.indexOf("{");
    const end = raw.lastIndexOf("}");
    if (start >= 0 && end > start) {
      try {
        return JSON.parse(raw.slice(start, end + 1)) as Record<string, unknown>;
      } catch {
        return null;
      }
    }
    return null;
  }
}

function fallbackPreviewHtml(designUrl: string, screenName: string, width = 390, height = 844): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=${width}, initial-scale=1, maximum-scale=1"/>
<title>${screenName}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body { width: 100%; height: 100%; background: #0b0d12; overflow: hidden; }
  .screen {
    position: relative;
    width: min(100vw, ${width}px);
    height: min(100vh, ${height}px);
    margin: 0 auto;
    background: #000 center/cover no-repeat url("${designUrl}");
    box-shadow: 0 0 0 1px rgba(255,255,255,.08);
  }
  .badge {
    position: absolute; top: 10px; left: 50%; transform: translateX(-50%);
    padding: 6px 12px; border-radius: 999px;
    background: rgba(12,16,28,.88); color: #cdd7ff; font: 600 11px/1.3 system-ui,sans-serif;
    border: 1px solid rgba(124,92,255,.45);
  }
</style>
</head>
<body>
  <div class="screen" role="img" aria-label="${screenName}">
    <div class="badge">Design reference — agent will match this exactly</div>
  </div>
</body>
</html>`;
}

function fallbackComponentCode(screenName: string, designUrl: string): string {
  const safe = screenName.replace(/[^a-zA-Z0-9]/g, "");
  return `import React from 'react';

/** Generated by UniLive's Design Agent — pixel reference preserved. */
export function DesignAgent${safe || "Screen"}() {
  return (
    <div
      className="relative mx-auto h-[100dvh] w-full max-w-[390px] overflow-hidden bg-black"
      data-design-agent-screen="${slugName(screenName)}"
      style={{
        backgroundImage: \`url('\${${JSON.stringify(designUrl)}}')\`,
        backgroundSize: 'cover',
        backgroundPosition: 'center top',
      }}
    >
      <div className="pointer-events-none absolute inset-x-0 top-3 flex justify-center">
        <span className="rounded-full border border-violet-500/45 bg-[#0c101c]/90 px-3 py-1 text-[11px] font-semibold text-[#cdd7ff]">
          ${screenName}
        </span>
      </div>
    </div>
  );
}
`;
}

async function runAgentVision(
  mimeType: string,
  dataBase64: string,
  screenName: string,
  designUrl: string,
  targetResourceId?: string | null,
): Promise<{
  spec: Record<string, unknown>;
  componentCode: string;
  previewHtml: string;
  catalogResourceId: string | null;
  fidelityNotes: string;
}> {
  const model = geminiModel();
  if (!model) {
    return {
      spec: { width: 390, height: 844, mode: "reference-overlay" },
      componentCode: fallbackComponentCode(screenName, designUrl),
      previewHtml: fallbackPreviewHtml(designUrl, screenName),
      catalogResourceId: targetResourceId || null,
      fidelityNotes: "GEMINI_API_KEY not set — stored your design as exact pixel reference. Add key for full code generation.",
    };
  }

  const prompt = `You are UniLive's Design Agent. Convert this UI/UX design into a fully working mobile app screen.

CRITICAL RULES:
- Match the uploaded design EXACTLY: layout, colors, typography, spacing, icons, shadows, gradients.
- Do NOT redesign, simplify, or substitute different UI patterns.
- Output must look identical to the design at 390px width (mobile).
- Use React 18 + Tailwind CSS utility classes in componentCode.
- previewHtml must be a standalone HTML document with inline CSS that renders pixel-identical to the design.
- Buttons/links must be functional (onClick handlers that console.log action names).
- Brand name is always spelled: UniLive's

Return ONLY valid JSON (no markdown outside the JSON object):
{
  "screenName": string,
  "spec": { "width": number, "height": number, "colors": string[], "fonts": string[], "regions": [{ "id": string, "label": string, "role": string }] },
  "componentCode": "complete React TSX file as a string",
  "previewHtml": "complete standalone HTML document as a string",
  "catalogResourceId": "${targetResourceId || "experience.design-agent.generated"}",
  "fidelityNotes": "brief note on what was preserved"
}

Screen name hint: ${screenName}`;

  const result = await generateText({
    model,
    maxOutputTokens: 8192,
    messages: [
      {
        role: "user",
        content: [
          { type: "text", text: prompt },
          { type: "image", image: `data:${mimeType};base64,${dataBase64}` },
        ],
      },
    ],
  }).catch((err: unknown) => {
    const message = err instanceof Error ? err.message : String(err);
    return { text: "", error: message } as { text: string; error?: string };
  });

  if ("error" in result && result.error) {
    return {
      spec: { width: 390, height: 844, agentError: result.error },
      componentCode: fallbackComponentCode(screenName, designUrl),
      previewHtml: fallbackPreviewHtml(designUrl, screenName),
      catalogResourceId: targetResourceId || null,
      fidelityNotes: `Agent unavailable (${result.error}) — stored exact design reference.`,
    };
  }

  const parsed = extractJson(result.text);
  if (!parsed) {
    return {
      spec: { width: 390, height: 844, parseError: true },
      componentCode: fallbackComponentCode(screenName, designUrl),
      previewHtml: fallbackPreviewHtml(designUrl, screenName),
      catalogResourceId: targetResourceId || null,
      fidelityNotes: "Agent response was not JSON — using exact design image overlay fallback.",
    };
  }

  return {
    spec: (parsed.spec as Record<string, unknown>) || {},
    componentCode: String(parsed.componentCode || fallbackComponentCode(screenName, designUrl)),
    previewHtml: String(parsed.previewHtml || fallbackPreviewHtml(designUrl, screenName)),
    catalogResourceId: typeof parsed.catalogResourceId === "string" ? parsed.catalogResourceId : targetResourceId || null,
    fidelityNotes: String(parsed.fidelityNotes || "Design converted with fidelity preservation."),
  };
}

export async function importDesignAgent(input: {
  fileName: string;
  mimeType: string;
  dataBase64: string;
  screenName?: string;
  targetResourceId?: string | null;
  actorId: string;
}): Promise<DesignAgentJob> {
  if (!agentEnabled()) {
    throw Object.assign(new Error("design agent local only"), { status: 404, code: "error.notFound" });
  }

  const id = createHash("sha256")
    .update(`${input.fileName}:${Date.now()}:${Math.random()}`)
    .digest("hex")
    .slice(0, 16);
  const screenName = input.screenName?.trim() || input.fileName.replace(/\.[^.]+$/, "") || "Uploaded screen";
  const assetId = `asset.design.${slugName(input.fileName)}.${Date.now()}`;

  const asset = uploadLocalAsset(
    {
      assetId,
      fileName: input.fileName,
      mimeType: input.mimeType,
      dataBase64: input.dataBase64,
    },
    input.actorId,
  );

  const designPreviewUrl = `/api/admin/assets/${asset.id}/content`;

  let job: DesignAgentJob = {
    id,
    status: "running",
    screenName,
    fileName: input.fileName,
    mimeType: input.mimeType,
    designAssetId: asset.id,
    designPreviewUrl,
    targetResourceId: input.targetResourceId || null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  writeJob(job);

  try {
    const out = await runAgentVision(
      input.mimeType,
      input.dataBase64,
      screenName,
      designPreviewUrl,
      input.targetResourceId,
    );

    const cs = createChangeSet(
      {
        title: `Design Agent — ${screenName}`,
        description: out.fidelityNotes,
        targetEnvironment: "local",
        baseSnapshotId: "snapshot.bundled.default",
      },
      input.actorId,
    );

    const resourceId = out.catalogResourceId || input.targetResourceId || `experience.design-agent.${slugName(screenName)}`;
    addOrUpdateItem(
      cs.id,
      {
        resourceType: "ui.experience",
        resourceId,
        operation: "update",
        patch: {
          name: screenName,
          designAgentJobId: id,
          designAssetId: asset.id,
          designPreviewUrl,
          spec: out.spec,
          componentCode: out.componentCode,
          previewHtml: out.previewHtml,
          fidelityNotes: out.fidelityNotes,
          note: "Generated by Design Agent — layout matches uploaded design",
        },
      },
      input.actorId,
    );

    job = {
      ...job,
      status: "ready",
      spec: out.spec,
      componentCode: out.componentCode,
      previewHtml: out.previewHtml,
      catalogResourceId: resourceId,
      fidelityNotes: out.fidelityNotes,
      changeSetId: cs.id,
      updatedAt: new Date().toISOString(),
    };
    writeJob(job);
    return job;
  } catch (e) {
    job = {
      ...job,
      status: "failed",
      error: e instanceof Error ? e.message : String(e),
      updatedAt: new Date().toISOString(),
    };
    writeJob(job);
    throw e;
  }
}
