const PIPELINES: Record<string, string> = {
  "ui.experience": "pipeline.ui-resource",
  "ui.node": "pipeline.ui-resource",
  "ui.component": "pipeline.ui-resource",
  "ui.element": "pipeline.ui-resource",
  "ui.layout": "pipeline.ui-resource",
  "ui.theme": "pipeline.ui-resource",
  "ui.token-set": "pipeline.ui-resource",
  "ui.motion": "pipeline.ui-resource",
  "ui.mockup": "pipeline.ui-resource",
  "ui.design": "pipeline.ui-resource",
  "ui.action": "pipeline.executable-resource",
  "ui.data-binding": "pipeline.executable-resource",
  "ui.asset": "pipeline.media-resource",
  "ui.translation-key": "pipeline.translation-resource",
  "ui.translation-catalog": "pipeline.translation-resource",
  "session.snapshot": "pipeline.session-assignment",
  "session.assignment": "pipeline.session-assignment",
  "session.preset": "pipeline.session-assignment",
  "config.public-runtime": "pipeline.runtime-config",
  "config.private-reference": "pipeline.runtime-config",
  "config.feature-flag": "pipeline.runtime-config",
  "config.provider": "pipeline.runtime-config",
  "config.secret-reference": "pipeline.secret-reference",
  "gift.definition": "pipeline.gift-resource",
  "gift.pricing": "pipeline.gift-resource",
  "face-effect.definition": "pipeline.face-effect-resource",
  "beauty-effect.definition": "pipeline.face-effect-resource",
  "animation.pack": "pipeline.animation-resource",
  "effect.renderer": "pipeline.executable-resource",
  "performance.profile": "pipeline.performance-certification",
  "runtime.bundle": "pipeline.performance-certification",
  "pipeline.definition": "pipeline.ui-resource",
  "permission.definition": "pipeline.ui-resource",
  "fallback.definition": "pipeline.ui-resource",
};

export function pipelineForType(type: string): string {
  return PIPELINES[type] || "";
}
