export const ADMIN_RESOURCE_TYPES = [
  "ui.experience",
  "ui.node",
  "ui.component",
  "ui.element",
  "ui.layout",
  "ui.theme",
  "ui.token-set",
  "ui.asset",
  "ui.motion",
  "ui.mockup",
  "ui.design",
  "ui.translation-key",
  "ui.translation-catalog",
  "ui.action",
  "ui.data-binding",
  "session.snapshot",
  "session.assignment",
  "session.preset",
  "config.public-runtime",
  "config.private-reference",
  "config.feature-flag",
  "config.provider",
  "config.secret-reference",
  "gift.definition",
  "gift.pricing",
  "face-effect.definition",
  "beauty-effect.definition",
  "animation.pack",
  "effect.renderer",
  "performance.profile",
  "runtime.bundle",
  "pipeline.definition",
  "permission.definition",
  "fallback.definition",
] as const;

export type AdminResourceType = (typeof ADMIN_RESOURCE_TYPES)[number];

export const CHANGE_SET_TYPE_ALIAS: Record<string, string> = {
  "ui.token-set": "ui.token",
  "ui.translation-key": "ui.translation",
  "ui.translation-catalog": "ui.translation",
  "session.snapshot": "ui.snapshot",
  "session.assignment": "ui.assignment",
  "session.preset": "ui.assignment",
  "config.public-runtime": "runtime.config",
  "config.private-reference": "runtime.config",
  "config.feature-flag": "runtime.feature_flag",
  "config.provider": "runtime.provider",
  "config.secret-reference": "runtime.secret_reference",
  "gift.definition": "gift.definition",
  "gift.pricing": "gift.pricing",
  "face-effect.definition": "face-effect.definition",
  "beauty-effect.definition": "beauty-effect.definition",
  "animation.pack": "animation.pack",
  "effect.renderer": "effect.renderer",
  "performance.profile": "performance.profile",
  "runtime.bundle": "runtime.bundle",
  "ui.action": "ui.component",
  "ui.data-binding": "ui.component",
};
