import type { ComponentType } from 'react';
import type { ComponentId } from './componentIds';
import { isRegisteredComponentId } from './componentIds';
import type { ActionId } from './actionRegistry';
import type { BindingId } from './bindingRegistry';

export type RegisteredComponentMeta = {
  id: ComponentId;
  version: number;
  supportedActions: ActionId[];
  bindings: BindingId[];
  fallbackComponentId: ComponentId;
};

export const COMPONENT_REGISTRY: Record<ComponentId, RegisteredComponentMeta> = {
  'navigation.bottom.v1': {
    id: 'navigation.bottom.v1',
    version: 1,
    supportedActions: ['navigation.open'],
    bindings: [],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'profile.header.v1': {
    id: 'profile.header.v1',
    version: 1,
    supportedActions: ['profile.follow', 'profile.open'],
    bindings: ['profile.header', 'profile.actions'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'profile.card.v1': {
    id: 'profile.card.v1',
    version: 1,
    supportedActions: ['profile.open'],
    bindings: ['profile.header'],
    fallbackComponentId: 'profile.header.v1',
  },
  'profile.screen.v1': {
    id: 'profile.screen.v1',
    version: 1,
    supportedActions: ['profile.follow', 'profile.open'],
    bindings: ['profile.header'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'feed.post-card.v1': {
    id: 'feed.post-card.v1',
    version: 1,
    supportedActions: ['profile.open'],
    bindings: [],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'feed.screen.v1': {
    id: 'feed.screen.v1',
    version: 1,
    supportedActions: ['navigation.open'],
    bindings: [],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'chat.thread-row.v1': {
    id: 'chat.thread-row.v1',
    version: 1,
    supportedActions: ['chat.openThread'],
    bindings: ['chat.threadList'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'chat.message-bubble.v1': {
    id: 'chat.message-bubble.v1',
    version: 1,
    supportedActions: ['chat.sendMessage'],
    bindings: ['chat.activeThread'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'chat.inbox.v1': {
    id: 'chat.inbox.v1',
    version: 1,
    supportedActions: ['chat.openThread', 'chat.sendMessage'],
    bindings: ['chat.threadList', 'chat.activeThread'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'live.room-header.v1': {
    id: 'live.room-header.v1',
    version: 1,
    supportedActions: ['live.close', 'profile.open'],
    bindings: ['live.header'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'live.viewer-counter.v1': {
    id: 'live.viewer-counter.v1',
    version: 1,
    supportedActions: [],
    bindings: ['live.header'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'live.audio-seat.v1': {
    id: 'live.audio-seat.v1',
    version: 1,
    supportedActions: ['seat.request', 'seat.leave', 'profile.open'],
    bindings: ['live.seats'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'live.video-seat.v1': {
    id: 'live.video-seat.v1',
    version: 1,
    supportedActions: ['seat.request', 'seat.leave', 'profile.open'],
    bindings: ['live.seats'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'live.gift-panel.v1': {
    id: 'live.gift-panel.v1',
    version: 1,
    supportedActions: ['gift.send'],
    bindings: ['live.giftPanel'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'live.pk-scoreboard.v1': {
    id: 'live.pk-scoreboard.v1',
    version: 1,
    supportedActions: ['pk.invite', 'pk.accept'],
    bindings: ['live.pk'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'live.screen.v1': {
    id: 'live.screen.v1',
    version: 1,
    supportedActions: ['live.join', 'live.leave', 'gift.send', 'seat.request'],
    bindings: ['live.header', 'live.seats', 'live.pk', 'live.giftPanel'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'wallet.balance-card.v1': {
    id: 'wallet.balance-card.v1',
    version: 1,
    supportedActions: ['wallet.purchase'],
    bindings: ['wallet.summary'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'wallet.balance-card.compact': {
    id: 'wallet.balance-card.compact',
    version: 1,
    supportedActions: ['wallet.purchase'],
    bindings: ['wallet.summary'],
    fallbackComponentId: 'wallet.balance-card.v1',
  },
  'wallet.coin-package.v1': {
    id: 'wallet.coin-package.v1',
    version: 1,
    supportedActions: ['wallet.purchase'],
    bindings: ['wallet.packages'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'wallet.screen.v1': {
    id: 'wallet.screen.v1',
    version: 1,
    supportedActions: ['wallet.purchase'],
    bindings: ['wallet.summary', 'wallet.packages'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'notifications.list.v1': {
    id: 'notifications.list.v1',
    version: 1,
    supportedActions: ['notification.markRead'],
    bindings: ['notifications.list'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'settings.screen.v1': {
    id: 'settings.screen.v1',
    version: 1,
    supportedActions: [],
    bindings: ['settings.form'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'auth.login.v1': {
    id: 'auth.login.v1',
    version: 1,
    supportedActions: [],
    bindings: [],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'auth.signup.v1': {
    id: 'auth.signup.v1',
    version: 1,
    supportedActions: [],
    bindings: [],
    fallbackComponentId: 'auth.login.v1',
  },
  'primitive.button.v1': { id: 'primitive.button.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.icon-button.v1': { id: 'primitive.icon-button.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'primitive.button.v1' },
  'primitive.icon.v1': { id: 'primitive.icon.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.input.v1': { id: 'primitive.input.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.label.v1': { id: 'primitive.label.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.toggle.v1': { id: 'primitive.toggle.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.checkbox.v1': { id: 'primitive.checkbox.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.radio.v1': { id: 'primitive.radio.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.slider.v1': { id: 'primitive.slider.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.avatar.v1': { id: 'primitive.avatar.v1', version: 1, supportedActions: ['profile.open'], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.badge.v1': { id: 'primitive.badge.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.ring.v1': { id: 'primitive.ring.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.frame.v1': { id: 'primitive.frame.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.image.v1': { id: 'primitive.image.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.video.v1': { id: 'primitive.video.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.animation.v1': { id: 'primitive.animation.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.modal.v1': { id: 'primitive.modal.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.sheet.v1': { id: 'primitive.sheet.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.dialog.v1': { id: 'primitive.dialog.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.menu.v1': { id: 'primitive.menu.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.dropdown.v1': { id: 'primitive.dropdown.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.tooltip.v1': { id: 'primitive.tooltip.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.popover.v1': { id: 'primitive.popover.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.banner.v1': { id: 'primitive.banner.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.toast.v1': { id: 'primitive.toast.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.tab.v1': { id: 'primitive.tab.v1', version: 1, supportedActions: ['navigation.open'], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.header.v1': { id: 'primitive.header.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.footer.v1': { id: 'primitive.footer.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.nav.v1': { id: 'primitive.nav.v1', version: 1, supportedActions: ['navigation.open'], bindings: [], fallbackComponentId: 'navigation.bottom.v1' },
  'primitive.panel.v1': { id: 'primitive.panel.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.list.v1': { id: 'primitive.list.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.grid.v1': { id: 'primitive.grid.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.row.v1': { id: 'primitive.row.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'primitive.column.v1': { id: 'primitive.column.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'state.loading.v1': { id: 'state.loading.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'state.empty.v1': { id: 'state.empty.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'state.error.v1': { id: 'state.error.v1', version: 1, supportedActions: [], bindings: [], fallbackComponentId: 'fallback.empty.v1' },
  'fallback.empty.v1': {
    id: 'fallback.empty.v1',
    version: 1,
    supportedActions: [],
    bindings: [],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'call.incoming.v1': {
    id: 'call.incoming.v1',
    version: 1,
    supportedActions: ['call.accept', 'call.reject'],
    bindings: ['call.incoming.caller'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'call.outgoing.v1': {
    id: 'call.outgoing.v1',
    version: 1,
    supportedActions: ['call.end'],
    bindings: ['call.active.participants'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'call.active.v1': {
    id: 'call.active.v1',
    version: 1,
    supportedActions: ['call.end', 'call.toggleMic', 'call.toggleCamera', 'call.switchCamera', 'call.toggleSpeaker', 'call.minimize', 'call.retry'],
    bindings: ['call.active.participants', 'call.active.duration'],
    fallbackComponentId: 'call.screen.v1',
  },
  'call.ended.v1': {
    id: 'call.ended.v1',
    version: 1,
    supportedActions: ['call.retry'],
    bindings: ['call.active.participants'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'call.participant-tile.v1': {
    id: 'call.participant-tile.v1',
    version: 1,
    supportedActions: [],
    bindings: ['call.active.participants'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'call.participant-grid.v1': {
    id: 'call.participant-grid.v1',
    version: 1,
    supportedActions: [],
    bindings: ['call.active.participants'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'call.controls.v1': {
    id: 'call.controls.v1',
    version: 1,
    supportedActions: ['call.end', 'call.toggleMic', 'call.toggleCamera', 'call.switchCamera', 'call.toggleSpeaker', 'call.invite', 'call.minimize', 'call.shareScreen'],
    bindings: ['call.active.participants'],
    fallbackComponentId: 'fallback.empty.v1',
  },
  'call.screen.v1': {
    id: 'call.screen.v1',
    version: 1,
    supportedActions: ['call.end', 'call.retry'],
    bindings: ['call.active.participants', 'call.active.duration', 'call.incoming.caller'],
    fallbackComponentId: 'fallback.empty.v1',
  },
};

export function getComponentMeta(id: string): RegisteredComponentMeta | null {
  if (!isRegisteredComponentId(id)) return null;
  return COMPONENT_REGISTRY[id];
}

export type PresentationRenderers = Partial<Record<ComponentId, ComponentType<{ viewModel?: unknown; onAction?: (id: ActionId, params: Record<string, unknown>) => void }>>>;
