/** Stable registered component IDs. New executable UI requires an app release. */

export const COMPONENT_IDS = [
  'navigation.bottom.v1',
  'profile.header.v1',
  'profile.card.v1',
  'profile.screen.v1',
  'feed.post-card.v1',
  'feed.screen.v1',
  'chat.thread-row.v1',
  'chat.message-bubble.v1',
  'chat.inbox.v1',
  'live.room-header.v1',
  'live.viewer-counter.v1',
  'live.audio-seat.v1',
  'live.video-seat.v1',
  'live.gift-panel.v1',
  'live.pk-scoreboard.v1',
  'live.screen.v1',
  'wallet.balance-card.v1',
  'wallet.balance-card.compact',
  'wallet.coin-package.v1',
  'wallet.screen.v1',
  'notifications.list.v1',
  'settings.screen.v1',
  'auth.login.v1',
  'auth.signup.v1',
  'primitive.button.v1',
  'primitive.icon-button.v1',
  'primitive.icon.v1',
  'primitive.input.v1',
  'primitive.label.v1',
  'primitive.toggle.v1',
  'primitive.checkbox.v1',
  'primitive.radio.v1',
  'primitive.slider.v1',
  'primitive.avatar.v1',
  'primitive.badge.v1',
  'primitive.ring.v1',
  'primitive.frame.v1',
  'primitive.image.v1',
  'primitive.video.v1',
  'primitive.animation.v1',
  'primitive.modal.v1',
  'primitive.sheet.v1',
  'primitive.dialog.v1',
  'primitive.menu.v1',
  'primitive.dropdown.v1',
  'primitive.tooltip.v1',
  'primitive.popover.v1',
  'primitive.banner.v1',
  'primitive.toast.v1',
  'primitive.tab.v1',
  'primitive.header.v1',
  'primitive.footer.v1',
  'primitive.nav.v1',
  'primitive.panel.v1',
  'primitive.list.v1',
  'primitive.grid.v1',
  'primitive.row.v1',
  'primitive.column.v1',
  'state.loading.v1',
  'state.empty.v1',
  'state.error.v1',
  'fallback.empty.v1',
  'call.incoming.v1',
  'call.outgoing.v1',
  'call.active.v1',
  'call.ended.v1',
  'call.participant-tile.v1',
  'call.participant-grid.v1',
  'call.controls.v1',
  'call.screen.v1',
] as const;

export type ComponentId = (typeof COMPONENT_IDS)[number];

export function isRegisteredComponentId(id: string): id is ComponentId {
  return (COMPONENT_IDS as readonly string[]).includes(id);
}
